version: '3'
services:
  panel:
    restart: always
    build: .
    expose:
      - ${PORT}
    env_file:
      - .env
    labels:
      - traefik.http.routers.panel.rule=Host("panel.apaudel.com")
#      - traefik.http.routers.panel.entrypoints=websecure,web
#      - traefik.http.routers.panel.tls.certresolver=certbot

networks:
  default:
    name: backend
