version: '3'
services:
  panel:
    build: .
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    command: "poetry run panel serve sales.py --port ${PORT}"
    environment:
      - VIRTUAL_HOST=${HOST}
      - BOKEH_ALLOW_WS_ORIGIN=${HOST}
    networks:
      - backend
networks:
  backend:
    external: true
