version: '3'
services:
  panel:
    restart: always
    build: .
    expose:
      - ${PORT}
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.panel.rule=Host("panel.paudel.me")
      - traefik.http.routers.panel.entrypoints=websecure
      - traefik.http.routers.panel.tls.certresolver=certbot

networks:
  default:
    name: backend
