version: '3'
services:
  panel:
    build: .
    expose:
      - ${PORT}
    command: "poetry run panel serve sales.py --port ${PORT}"
    environment:
      - VIRTUAL_HOST=panel.apaudel.com
    networks:
      - backend
networks:
  backend:
    external: true
